### ISSUE TITLE
Figure out image sizing issue

### ISSUE THREAD

**Issue by ncuenca** [ncuenca/shareBnB-backend#2]
This could be solved with image compression, downsizing the image before its loaded, limiting image size on the upload. Honestly unsure how to fix this but this is a big issue.

The user models in sis has an 4 photo fields to deal with this. Something to look at for inspiration - maybe we could implement this?

**Comment by ncuenca** [comment]
Sarah mentioned something called Pillow that could be helpful.

**Comment by mykeychain** [comment]
Here's the django documentation on ImageSpecField: 
https://django-imagekit.readthedocs.io/en/latest/
